import type { Metadata } from "next";
import { Roboto, Inter, Oswald} from "next/font/google";
import "../styles/globals.scss";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--roboto-font",
});

const inter = Inter({
  weight: ["400", "700", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: '--inter-font',
});

const oswald = Oswald({
  weight: ["400","500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: '--title-font',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme={'dark'}>
    <body className={`${inter.variable} ${roboto.variable} ${oswald.variable}`}>
        {children}
        <div id="root"></div>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
